# Generated by Django 3.1.7 on 2021-03-06 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('distance_from_transmitter', models.FloatField(validators=[django.core.validators.MinValueValidator(0.9)])),
            ],
        ),
    ]
