# Generated by Django 3.1.7 on 2021-03-06 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quasar_fire_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='distance_from_transmitter',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.9)]),
        ),
    ]
