# Generated by Django 3.1.7 on 2021-03-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quasar_fire_app', '0004_auto_20210306_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='message_received',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='distance_from_transmitter',
            field=models.FloatField(null=True),
        ),
    ]
