# Generated by Django 3.1.7 on 2021-03-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quasar_fire_app', '0005_auto_20210307_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
